### ISSUE TITLE
Bugs in objects game

### ISSUE THREAD

**Issue by tomekkorbak** [facebookresearch/EGG#18]
I found two bugs in the objects game:

1. Temperature updating does not work, because the `callback` variable is assigned a `None` here.
https://github.com/facebookresearch/EGG/blob/f0c3a70c26cd1c23a24f853189ac0d40687f3478/egg/zoo/objects_game/train.py#L171-L183

#17 will fix this.

2. `_fill_split` falls into infinite loop for some inputs, e.g. `perceptual_dimensions = [10, 10]`.
https://github.com/facebookresearch/EGG/blob/f0c3a70c26cd1c23a24f853189ac0d40687f3478/egg/zoo/objects_game/features.py#L79-L96

**Comment by eugene-kharitonov** [comment]
cc @robertodessi

**Comment by robertodessi** [comment]
Hey @tomekkorbak , thanks for working on EGG.

Re 2), what {train|valid|test} split sizes are you using?

**Comment by tomekkorbak** [comment]
@robertodessi, I used the default, i.e. 100000/1000/1000. I can now see the reason: there simply wasn't enough combinations to populate a dataset with size pre-defined to 100000. So it's my fault, I guess. (Although an AssertionError preventing the infinite loop would be nice).

**Comment by robertodessi** [comment]
I thought I had it but apparently is not working as expected 

https://github.com/facebookresearch/EGG/blob/f0c3a70c26cd1c23a24f853189ac0d40687f3478/egg/zoo/objects_game/features.py#L127

so thanks for spotting it.

Feel free to fix this in the PR, otherwise I could look into it next week.
I should be updating the game with a slightly better version that I'm currently using but I don't think it will happen very soon

**Comment by robertodessi** [comment]
I realized it should be as easy as swapping these two lines, my bad.

https://github.com/facebookresearch/EGG/blob/f0c3a70c26cd1c23a24f853189ac0d40687f3478/egg/zoo/objects_game/features.py#L126-L128

we should first do the check and then generate the tuples right?! :-)

**Comment by robertodessi** [comment]
#19 fixes the assertion error.
Thanks for spotting it.

**Comment by tomekkorbak** [comment]
I'm glad I could help!
